# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-10-28 03:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('case_id', models.AutoField(primary_key=True,
                                             serialize=False)),
                ('case_name', models.CharField(max_length=50)),
                ('request_type', models.CharField(max_length=50)),
                ('url', models.CharField(max_length=100)),
                ('case_bz', models.CharField(max_length=200)),
                ('request_data', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Case_suite',
            fields=[
                ('suite_id', models.AutoField(primary_key=True,
                                              serialize=False)),
                ('suite_name', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Ym',
            fields=[
                ('ym_id', models.AutoField(primary_key=True, serialize=False)),
                ('project_name', models.CharField(max_length=50, unique=True)),
                ('url_name', models.CharField(max_length=50)),
                ('bz', models.TextField(blank=True, max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='case_suite',
            name='project_name',
            field=models.ManyToManyField(default='', to='myapp.Ym'),
        ),
        migrations.AddField(
            model_name='case',
            name='project_name',
            field=models.ManyToManyField(default='', to='myapp.Ym'),
        ),
    ]
