# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-10-28 04:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20181028_0348'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='case_suite',
            name='status',
        ),
        migrations.AddField(
            model_name='case',
            name='isdelete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='case_suite',
            name='isdelete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ym',
            name='isdelete',
            field=models.BooleanField(default=False),
        ),
    ]
