# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-11-09 09:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20181028_0451'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='project_name',
            field=models.ManyToManyField(default='', related_name='tracks',
                                         to='myapp.Ym'),
        ),
    ]
