# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-11-10 04:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_auto_20181109_0901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='project_name',
            field=models.ManyToManyField(default='', to='myapp.Ym'),
        ),
    ]
