# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-11-11 07:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_auto_20181111_0152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='project_name',
            field=models.ForeignKey(default='',
                                    on_delete=django.db.models.deletion.CASCADE,
                                    to='myapp.Ym'),
        ),
    ]
