# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-11-13 14:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_auto_20181113_1257'),
    ]

    operations = [
        migrations.AddField(
            model_name='case_suite',
            name='bz',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='case_suite',
            name='case',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='case_suite',
            name='headers',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='case_suite',
            name='status',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='case_suite',
            name='yuming',
            field=models.CharField(default='', max_length=50),
        ),
    ]
