# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-11-14 03:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_auto_20181113_1406'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='case_name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='case_suite',
            name='case',
            field=models.ForeignKey(blank=True, default='', max_length=50, on_delete=django.db.models.deletion.CASCADE, related_name='suite_case_name', to='myapp.Case'),
        ),
        migrations.AlterField(
            model_name='case_suite',
            name='headers',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='case_suite',
            name='project_name',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, related_name='suite_project_name', to='myapp.Ym'),
        ),
        migrations.AlterField(
            model_name='case_suite',
            name='status',
            field=models.CharField(default='\u672a\u8fdb\u884c', max_length=50),
        ),
        migrations.AlterField(
            model_name='case_suite',
            name='yuming',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, related_name='suite_yuming', to='myapp.Ym'),
        ),
        migrations.AlterField(
            model_name='ym',
            name='url_name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
