# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-11-14 03:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_auto_20181114_0312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='case_name',
            field=models.CharField(max_length=50),
        ),
    ]
