# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-11-16 14:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0020_auto_20181115_1255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ym',
            name='project_name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
