# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-11-17 08:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0022_auto_20181116_1413'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='case_name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='case_suite',
            name='case',
            field=models.ForeignKey(default='', max_length=50, on_delete=django.db.models.deletion.CASCADE, related_name='suite_case_name', to='myapp.Case'),
        ),
        migrations.AlterField(
            model_name='case_suite',
            name='headers',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='case_suite',
            name='project_name',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='suite_project_name', to='myapp.Ym'),
        ),
        migrations.AlterField(
            model_name='case_suite',
            name='suite_name',
            field=models.CharField(error_messages={'unique': '\u5957\u4ef6\u540d\u79f0\u5df2\u5b58\u5728'}, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='case_suite',
            name='yuming',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='suite_yuming', to='myapp.Ym'),
        ),
        migrations.AlterField(
            model_name='ym',
            name='url_name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
