# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-11-18 08:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0025_auto_20181118_0634'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True,
                                        serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=100)),
                ('user', models.OneToOneField(
                    on_delete=django.db.models.deletion.CASCADE,
                    to='myapp.Login')),
            ],
        ),
        migrations.AlterField(
            model_name='case',
            name='case_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='case',
            name='project_name',
            field=models.ForeignKey(default='',
                                    error_messages={'blank':
                                                        '\u9879\u76ee\u540d'
                                                        '\u79f0\u4e0d'
                                                        '\u80fd\u4e3a\u7a7a'},
                                    on_delete=django.db.models.deletion.CASCADE,
                                    related_name='case_project_name',
                                    to='myapp.Ym'),
        ),
        migrations.AlterField(
            model_name='case_suite',
            name='suite_name',
            field=models.CharField(max_length=50),
        ),
    ]
