# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-11-18 12:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0028_auto_20181118_1229'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='case',
            name='project_name',
        ),
        migrations.RemoveField(
            model_name='case_suite',
            name='case',
        ),
        migrations.RemoveField(
            model_name='case_suite',
            name='project_name',
        ),
        migrations.RemoveField(
            model_name='case_suite',
            name='yuming',
        ),
        migrations.RemoveField(
            model_name='login',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='login',
            name='user_permissions',
        ),
        migrations.RemoveField(
            model_name='usertoken',
            name='user',
        ),
        migrations.DeleteModel(
            name='Case',
        ),
        migrations.DeleteModel(
            name='Case_suite',
        ),
        migrations.DeleteModel(
            name='Login',
        ),
        migrations.DeleteModel(
            name='UserToken',
        ),
        migrations.DeleteModel(
            name='Ym',
        ),
    ]
