# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-11-18 12:35
from __future__ import unicode_literals

import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
        ('myapp', '0032_auto_20181118_1233'),
    ]

    operations = [
        migrations.CreateModel(
            name='Login',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True,
                                                    verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False,
                                                     help_text='Designates that'
                                                               ' this user has '
                                                               'all permissions '
                                                               'without '
                                                               'explicitly '
                                                               'assigning '
                                                               'them.',
                                                     verbose_name='superuser '
                                                                  'status')),
                ('username', models.CharField(error_messages={'unique':
                                                                  'A user with '
                                                                  'that '
                                                                  'username '
                                                                  'already '
                                                                  'exists.'},
                                              help_text='Required. 150 '
                                                        'characters or fewer. '
                                                        'Letters, digits and '
                                                        '@/./+/-/_ only.',
                                              max_length=150, unique=True,
                                              validators=[django.contrib.auth
                                              .validators.
                                              ASCIIUsernameValidator()],
                                              verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=30,
                                                verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=30,
                                               verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254,
                                            verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False,
                                                 help_text='Designates whether '
                                                           'the user can log '
                                                           'into this admin '
                                                           'site.',
                                                 verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True,
                                                  help_text='Designates whether'
                                                            ' this user should '
                                                            'be treated as '
                                                            'active. '
                                                            'Unselect this '
                                                            'instead of '
                                                            'deleting '
                                                            'accounts.',
                                                  verbose_name='active')),
                ('date_joined', models.DateTimeField(
                    default=django.utils.timezone.now,
                    verbose_name='date joined')),
                ('user_id', models.AutoField(primary_key=True,
                                             serialize=False)),
                ('name', models.CharField(blank=True, max_length=100,
                                          unique=True)),
                ('password', models.CharField(blank=True, max_length=100)),
                ('groups', models.ManyToManyField(blank=True,
                                                  help_text='The groups this '
                                                            'user belongs to. '
                                                            'A user will get '
                                                            'all permissions '
                                                            'granted to each '
                                                            'of their groups.',
                                                  related_name='user_set',
                                                  related_query_name='user',
                                                  to='auth.Group',
                                                  verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True,
                                                            help_text='Specific'
                                                                      ' permiss'
                                                                      'ions for '
                                                                      'this us'
                                                                      'er.',
                                                            related_name='user_'
                                                                         'set',
                                                            related_query_name=
                                                            'user', to=
                                                            'auth.Permission',
                                                            verbose_name='user '
                                                                         'permi'
                                                                         'ssio'
                                                                         'ns')),
            ],
            options={
                'verbose_name': '\u7528\u6237',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Case',
            fields=[
                ('case_id', models.AutoField(primary_key=True,
                                             serialize=False)),
                ('case_name', models.CharField(max_length=50)),
                ('request_type', models.CharField(max_length=50)),
                ('url', models.CharField(max_length=100)),
                ('case_bz', models.CharField(blank=True, max_length=200)),
                ('request_data', models.CharField(default='', max_length=100)),
                ('isdelete', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Case_suite',
            fields=[
                ('suite_id', models.AutoField(primary_key=True,
                                              serialize=False)),
                ('suite_name', models.CharField(max_length=50)),
                ('headers', models.CharField(default='', max_length=50)),
                ('bz', models.CharField(blank=True, default='', max_length=200)),
                ('isdelete', models.BooleanField(default=False)),
                ('status', models.CharField(default='\u672a\u5f00\u59cb',
                                            max_length=50)),
                ('case', models.ForeignKey(default='', max_length=50,
                                           on_delete=django.db.models.deletion.
                                           CASCADE,
                                           related_name='suite_case_name',
                                           to='myapp.Case')),
            ],
        ),
        migrations.CreateModel(
            name='Ym',
            fields=[
                ('ym_id', models.AutoField(primary_key=True, serialize=False)),
                ('project_name', models.CharField(max_length=50)),
                ('url_name', models.CharField(max_length=50)),
                ('bz', models.TextField(blank=True, max_length=100)),
                ('isdelete', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='case_suite',
            name='project_name',
            field=models.ForeignKey(default='',
                                    on_delete=django.db.models.deletion.
                                    CASCADE,
                                    related_name='suite_project_name',
                                    to='myapp.Ym'),
        ),
        migrations.AddField(
            model_name='case_suite',
            name='yuming',
            field=models.ForeignKey(default='', on_delete=django.db.
                                    models.deletion.CASCADE,
                                    related_name='suite_yuming', to='myapp.Ym'),
        ),
        migrations.AddField(
            model_name='case',
            name='project_name',
            field=models.ForeignKey(default='',
                                    error_messages={'blank': '\u9879'
                                                             '\u76ee\u540d'
                                                             '\u79f0\u4e0d'
                                                             '\u80fd\u4e3a'
                                                             '\u7a7a'},
                                    on_delete=django.db.models.deletion.CASCADE,
                                    related_name='case_project_name',
                                    to='myapp.Ym'),
        ),
    ]
