# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-11-18 12:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0035_usertoken'),
    ]

    operations = [
        migrations.CreateModel(
            name='Login',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=100, unique=True)),
                ('password', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'verbose_name': '\u7528\u6237',
            },
        ),
        migrations.DeleteModel(
            name='UserToken',
        ),
    ]
