# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-11-24 02:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0043_auto_20181123_1531'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case_suite',
            name='headers',
            field=models.CharField(default='', max_length=200),
        ),
    ]
