# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-11-24 15:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0044_auto_20181124_0211'),
    ]

    operations = [
        migrations.AddField(
            model_name='login',
            name='isdelete',
            field=models.BooleanField(default=False),
        ),
    ]
