# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-11-25 02:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0047_auto_20181125_0153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='login',
            name='first_name',
            field=models.CharField(blank=True, max_length=30,
                                   verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='login',
            name='last_name',
            field=models.CharField(blank=True, max_length=30,
                                   verbose_name='last name'),
        ),
    ]
